#spring.application.name=journal
#spring.mongodb.uri=mongodb+srv://MongoDBAtlas:MongoDB999900@cluster0.0z2xbvn.mongodb.net/?appName=Cluster0
#spring.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#server.port=8081
#server.servlet.context-path=/journal
#spring.data.mongodb.username=123
#spring.data.mongodb.password=123
